import dataSource from '../../../database/data-source';
import { Formulario } from '../entities/formulario.entity';
import { FormularioPregunta } from '../entities/formulario-pregunta.entity';

// Generado a partir de FORM_TEMPLATES del PMV (la "receta" de cada
// plantilla — TDD sección 6.2).
//
// Formato simplificado (mejora post-v2.23, corrección de un error grave):
// cada validación es solo {formula, msgFail, msgOk} — antes también se
// escribía a mano una lista de "tokens" en paralelo, y 20 de los 37
// campos del formulario activo tenían esos tokens mal escritos (una
// validación "menor o igual" codificada como una cadena rara que el
// motor interpretaba mal), aunque su "formula" en texto SIEMPRE estuvo
// bien escrita. Resultado real: campos con datos correctos se marcaban
// en rojo. Ahora "tokens" ni se escribe ni se guarda — ValidacionService
// los calcula siempre desde "formula" (parsearFormula), así que no puede
// volver a existir una segunda copia que se desincronice. Revisar que
// una fórmula esté bien escrita es, ahora, tan simple como leerla: "C09
// <= C08" se entiende a simple vista.
export const FORMULARIOS_SEED: Partial<Formulario>[] = [
{ id: "seguimiento_disciplinario_37", label: "Avance Sumarios v2 (37 preguntas)", descripcion: null, icono: "📋" },
  { id: "seguimiento_disciplinario", label: "Avance Sumarios v2 (44 preguntas, con anexos)", descripcion: null, icono: "📋" },
];

export const FORMULARIO_PREGUNTAS_SEED: Partial<FormularioPregunta>[] = [
{ formularioId: "seguimiento_disciplinario_37", preguntaId: "Q01", posicionCanonica: 1, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q02", posicionCanonica: 2, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q03", posicionCanonica: 3, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q04", posicionCanonica: 4, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q05", posicionCanonica: 5, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q06", posicionCanonica: 6, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q07", posicionCanonica: 7, validaciones: [{ formula: "C07 + C08 = C06", msgFail: "La suma de campos 7 y 8 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "YA_NO_ESTAN", posicionCanonica: 8, validaciones: [{ formula: "C07 + C08 = C06", msgFail: "La suma de campos 7 y 8 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CESARON", posicionCanonica: 9, validaciones: [{ formula: "C09 <= C08", msgFail: "Campo 9 debe ser menor o igual al campo 8", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "YA_SUMARIADOS", posicionCanonica: 10, validaciones: [{ formula: "C10 <= C06", msgFail: "Campo 10 debe ser menor o igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q15", posicionCanonica: 11, validaciones: [{ formula: "C11 + C12 = C06", msgFail: "La suma de campos 11 y 12 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q16", posicionCanonica: 12, validaciones: [{ formula: "C11 + C12 = C06", msgFail: "La suma de campos 11 y 12 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q17", posicionCanonica: 13, validaciones: [{ formula: "C13 + C14 = C06", msgFail: "La suma de campos 13 y 14 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q18", posicionCanonica: 14, validaciones: [{ formula: "C13 + C14 = C06", msgFail: "La suma de campos 13 y 14 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q19", posicionCanonica: 15, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q20", posicionCanonica: 16, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q21", posicionCanonica: 17, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q22", posicionCanonica: 18, validaciones: [] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q23", posicionCanonica: 19, validaciones: [{ formula: "C19 <= C06", msgFail: "Casos a investigar (19) debe ser menor o igual a funcionarios involucrados (6)", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_9", posicionCanonica: 20, validaciones: [{ formula: "C20 <= C19", msgFail: "El campo 20 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_10", posicionCanonica: 21, validaciones: [{ formula: "C21 <= C19", msgFail: "El campo 21 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_13", posicionCanonica: 22, validaciones: [{ formula: "C22 <= C19", msgFail: "El campo 22 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_14", posicionCanonica: 23, validaciones: [{ formula: "C23 <= C19", msgFail: "El campo 23 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_15", posicionCanonica: 24, validaciones: [{ formula: "C24 <= C19", msgFail: "El campo 24 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_16", posicionCanonica: 25, validaciones: [{ formula: "C25 <= C19", msgFail: "El campo 25 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CIC_21", posicionCanonica: 26, validaciones: [{ formula: "C26 <= C19", msgFail: "El campo 26 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q37", posicionCanonica: 27, validaciones: [{ formula: "C27 <= C19", msgFail: "Sumarios instruidos (27) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C27 >= C32", msgFail: "❌ ERROR: Los casos cerrados (32) no pueden ser más que los sumarios instruidos (27). Revisa los datos.", msgOk: "✅ Correcto: Los sumarios instruidos (27) son mayores o iguales que los casos cerrados (32)." }, { formula: "C28 + C29 + C30 + C31 + C32 = C27", msgFail: "La suma de los campos 28, 29, 30, 31, 32 debe ser igual al campo 27", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q38", posicionCanonica: 28, validaciones: [{ formula: "C28 <= C19", msgFail: "Procesos en curso (28) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C28 + C29 + C30 + C31 + C32 = C27", msgFail: "La suma de los campos 28, 29, 30, 31, 32 debe ser igual al campo 27", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q42", posicionCanonica: 29, validaciones: [{ formula: "C29 <= C19", msgFail: "Procesos resueltos (29) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C28 + C29 + C30 + C31 + C32 = C27", msgFail: "La suma de los campos 28, 29, 30, 31, 32 debe ser igual al campo 27", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q43", posicionCanonica: 30, validaciones: [{ formula: "C30 <= C19", msgFail: "Procesos impugnados (30) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C28 + C29 + C30 + C31 + C32 = C27", msgFail: "La suma de los campos 28, 29, 30, 31, 32 debe ser igual al campo 27", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q44", posicionCanonica: 31, validaciones: [{ formula: "C31 <= C19", msgFail: "Enviados a CGR (31) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C28 + C29 + C30 + C31 + C32 = C27", msgFail: "La suma de los campos 28, 29, 30, 31, 32 debe ser igual al campo 27", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q45", posicionCanonica: 32, validaciones: [{ formula: "C32 <= C19", msgFail: "Procesos cerrados (32) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C32 <= C27", msgFail: "❌ ERROR: Los casos cerrados (32) no pueden ser más que los sumarios instruidos (27). Revisa los datos.", msgOk: "✅ Correcto: Los casos cerrados (32) son menores o iguales que los sumarios instruidos (27)." }, { formula: "C28 + C29 + C30 + C31 + C32 = C27", msgFail: "La suma de los campos 28, 29, 30, 31, 32 debe ser igual al campo 27", msgOk: "Validación correcta" }, { formula: "C33 + C34 + C35 + C36 + C37 = C32", msgFail: "La suma de los campos 33, 34, 35, 36, 37 debe ser igual al campo 32", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "CENSURA", posicionCanonica: 33, validaciones: [{ formula: "C33 <= C32", msgFail: "Sanción censura (33) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C33 + C34 + C35 + C36 + C37 = C32", msgFail: "La suma de los campos 33, 34, 35, 36, 37 debe ser igual al campo 32", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q48", posicionCanonica: 34, validaciones: [{ formula: "C34 <= C32", msgFail: "Sanción multa (34) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C33 + C34 + C35 + C36 + C37 = C32", msgFail: "La suma de los campos 33, 34, 35, 36, 37 debe ser igual al campo 32", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q49", posicionCanonica: 35, validaciones: [{ formula: "C35 <= C32", msgFail: "Sanción suspensión (35) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C33 + C34 + C35 + C36 + C37 = C32", msgFail: "La suma de los campos 33, 34, 35, 36, 37 debe ser igual al campo 32", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q50", posicionCanonica: 36, validaciones: [{ formula: "C36 <= C32", msgFail: "Sanción destitución (36) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C33 + C34 + C35 + C36 + C37 = C32", msgFail: "La suma de los campos 33, 34, 35, 36, 37 debe ser igual al campo 32", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario_37", preguntaId: "Q51", posicionCanonica: 37, validaciones: [{ formula: "C37 <= C32", msgFail: "Sin sanción (37) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C33 + C34 + C35 + C36 + C37 = C32", msgFail: "La suma de los campos 33, 34, 35, 36, 37 debe ser igual al campo 32", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q01", posicionCanonica: 1, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q02", posicionCanonica: 2, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q03", posicionCanonica: 3, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q04", posicionCanonica: 4, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q05", posicionCanonica: 5, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q06", posicionCanonica: 6, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q07", posicionCanonica: 7, validaciones: [{ formula: "C07 + C08 = C06", msgFail: "La suma de campos 7 y 8 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "YA_NO_ESTAN", posicionCanonica: 8, validaciones: [{ formula: "C07 + C08 = C06", msgFail: "La suma de campos 7 y 8 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CESARON", posicionCanonica: 9, validaciones: [{ formula: "C09 <= C08", msgFail: "Campo 9 debe ser menor o igual al campo 8", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "YA_SUMARIADOS", posicionCanonica: 10, validaciones: [{ formula: "C10 <= C06", msgFail: "Campo 10 debe ser menor o igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q15", posicionCanonica: 11, validaciones: [{ formula: "C11 + C12 = C06", msgFail: "La suma de campos 11 y 12 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q16", posicionCanonica: 12, validaciones: [{ formula: "C11 + C12 = C06", msgFail: "La suma de campos 11 y 12 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q17", posicionCanonica: 13, validaciones: [{ formula: "C13 + C14 = C06", msgFail: "La suma de campos 13 y 14 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q18", posicionCanonica: 14, validaciones: [{ formula: "C13 + C14 = C06", msgFail: "La suma de campos 13 y 14 debe ser igual al campo 6", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q19", posicionCanonica: 15, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q20", posicionCanonica: 16, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q21", posicionCanonica: 17, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q22", posicionCanonica: 18, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q23", posicionCanonica: 19, validaciones: [{ formula: "C19 <= C06", msgFail: "Casos a investigar (19) debe ser menor o igual a funcionarios involucrados (6)", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_9", posicionCanonica: 20, validaciones: [{ formula: "C20 <= C19", msgFail: "El campo 20 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_10", posicionCanonica: 21, validaciones: [{ formula: "C21 <= C19", msgFail: "El campo 21 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_13", posicionCanonica: 22, validaciones: [{ formula: "C22 <= C19", msgFail: "El campo 22 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_14", posicionCanonica: 23, validaciones: [{ formula: "C23 <= C19", msgFail: "El campo 23 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_15", posicionCanonica: 24, validaciones: [{ formula: "C24 <= C19", msgFail: "El campo 24 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_16", posicionCanonica: 25, validaciones: [{ formula: "C25 <= C19", msgFail: "El campo 25 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CIC_21", posicionCanonica: 26, validaciones: [{ formula: "C26 <= C19", msgFail: "El campo 26 no puede ser mayor al campo 19 (casos a investigar). Una persona puede estar en varias CIC, pero no más de una vez en la misma CIC.", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q56", posicionCanonica: 27, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q57", posicionCanonica: 28, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q37", posicionCanonica: 29, validaciones: [{ formula: "C27 <= C19", msgFail: "Sumarios instruidos (27) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C27 >= C32", msgFail: "❌ ERROR: Los casos cerrados (32) no pueden ser más que los sumarios instruidos (27). Revisa los datos.", msgOk: "✅ Correcto: Los sumarios instruidos (27) son mayores o iguales que los casos cerrados (32)." }, { formula: "C31 + C33 + C34 + C35 + C36 = C29", msgFail: "La suma de los campos 31, 33, 34, 35, 36 debe ser igual al campo 29", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q58", posicionCanonica: 30, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q38", posicionCanonica: 31, validaciones: [{ formula: "C28 <= C19", msgFail: "Procesos en curso (28) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C31 + C33 + C34 + C35 + C36 = C29", msgFail: "La suma de los campos 31, 33, 34, 35, 36 debe ser igual al campo 29", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q59", posicionCanonica: 32, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q42", posicionCanonica: 33, validaciones: [{ formula: "C29 <= C19", msgFail: "Procesos resueltos (29) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C31 + C33 + C34 + C35 + C36 = C29", msgFail: "La suma de los campos 31, 33, 34, 35, 36 debe ser igual al campo 29", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q43", posicionCanonica: 34, validaciones: [{ formula: "C30 <= C19", msgFail: "Procesos impugnados (30) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C31 + C33 + C34 + C35 + C36 = C29", msgFail: "La suma de los campos 31, 33, 34, 35, 36 debe ser igual al campo 29", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q44", posicionCanonica: 35, validaciones: [{ formula: "C31 <= C19", msgFail: "Enviados a CGR (31) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C31 + C33 + C34 + C35 + C36 = C29", msgFail: "La suma de los campos 31, 33, 34, 35, 36 debe ser igual al campo 29", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q45", posicionCanonica: 36, validaciones: [{ formula: "C32 <= C19", msgFail: "Procesos cerrados (32) debe ser menor o igual a casos a investigar (19)", msgOk: "Validación correcta" }, { formula: "C32 <= C27", msgFail: "❌ ERROR: Los casos cerrados (32) no pueden ser más que los sumarios instruidos (27). Revisa los datos.", msgOk: "✅ Correcto: Los casos cerrados (32) son menores o iguales que los sumarios instruidos (27)." }, { formula: "C31 + C33 + C34 + C35 + C36 = C29", msgFail: "La suma de los campos 31, 33, 34, 35, 36 debe ser igual al campo 29", msgOk: "Validación correcta" }, { formula: "C38 + C39 + C40 + C41 + C42 = C36", msgFail: "La suma de los campos 38, 39, 40, 41, 42 debe ser igual al campo 36", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q60", posicionCanonica: 37, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "CENSURA", posicionCanonica: 38, validaciones: [{ formula: "C33 <= C32", msgFail: "Sanción censura (33) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C38 + C39 + C40 + C41 + C42 = C36", msgFail: "La suma de los campos 38, 39, 40, 41, 42 debe ser igual al campo 36", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q48", posicionCanonica: 39, validaciones: [{ formula: "C34 <= C32", msgFail: "Sanción multa (34) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C38 + C39 + C40 + C41 + C42 = C36", msgFail: "La suma de los campos 38, 39, 40, 41, 42 debe ser igual al campo 36", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q49", posicionCanonica: 40, validaciones: [{ formula: "C35 <= C32", msgFail: "Sanción suspensión (35) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C38 + C39 + C40 + C41 + C42 = C36", msgFail: "La suma de los campos 38, 39, 40, 41, 42 debe ser igual al campo 36", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q50", posicionCanonica: 41, validaciones: [{ formula: "C36 <= C32", msgFail: "Sanción destitución (36) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C38 + C39 + C40 + C41 + C42 = C36", msgFail: "La suma de los campos 38, 39, 40, 41, 42 debe ser igual al campo 36", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q51", posicionCanonica: 42, validaciones: [{ formula: "C37 <= C32", msgFail: "Sin sanción (37) debe ser menor o igual a procesos cerrados (32)", msgOk: "Validación correcta" }, { formula: "C38 + C39 + C40 + C41 + C42 = C36", msgFail: "La suma de los campos 38, 39, 40, 41, 42 debe ser igual al campo 36", msgOk: "Validación correcta" }] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q61", posicionCanonica: 43, validaciones: [] },
  { formularioId: "seguimiento_disciplinario", preguntaId: "Q62", posicionCanonica: 44, validaciones: [] },
];

export async function seedFormularios() {
  const formularioRepo = dataSource.getRepository(Formulario);
  const recetaRepo = dataSource.getRepository(FormularioPregunta);
  await formularioRepo.save(FORMULARIOS_SEED);
  await recetaRepo.save(FORMULARIO_PREGUNTAS_SEED);
  console.log(`${FORMULARIOS_SEED.length} formularios y ${FORMULARIO_PREGUNTAS_SEED.length} items de receta creados.`);
}
